# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf_test/temp2.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

## descriptor 描述符



DESCRIPTOR = _descriptor.FileDescriptor(  ##描述符 =描述符 .文件描述Descriptor
  name='protobuf_test/temp2.proto', ## 名字
  package='',## 包
  serialized_pb=_b('\n\x14protobuf/temp2.proto\"\xde\x01\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x02(\t\x12\x13\n\x0bpage_number\x18\x02 \x01(\x05\x12\x1b\n\x0fresult_per_page\x18\x03 \x01(\x05:\x02\x31\x30\x12\x30\n\x06\x63orpus\x18\x04 \x01(\x0e\x32\x15.SearchRequest.Corpus:\tUNIVERSAL\"Z\n\x06\x43orpus\x12\r\n\tUNIVERSAL\x10\x00\x12\x07\n\x03WEB\x10\x01\x12\n\n\x06IMAGES\x10\x02\x12\t\n\x05LOCAL\x10\x03\x12\x08\n\x04NEWS\x10\x04\x12\x0c\n\x08PRODUCTS\x10\x05\x12\t\n\x05VIDEO\x10\x06')
)   ##序列化



_sym_db.RegisterFileDescriptor(DESCRIPTOR)  ##register 注册文件描述  开始（descriptor）


## 枚举类型  所有成员的 开始   是指是一个元组
_SEARCHREQUEST_CORPUS = _descriptor.EnumDescriptor(  ##corpus是一个枚举的类名  消息类_枚举的类名
  name='Corpus',## 枚举的类名
  full_name='SearchRequest.Corpus',## 所有的文件名 命名规则是消息类+枚举类
  filename=None, ##
  file=DESCRIPTOR, ## 文件是描述符
  values=[  ## values 是属性  代指的是 枚举中所有的列举
    _descriptor.EnumValueDescriptor(    ## 描述符.枚举 值 描述
      name='UNIVERSAL', index=0, number=0, ## 名称 索引 数目  选择  类型
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WEB', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IMAGES', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOCAL', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NEWS', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRODUCTS', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VIDEO', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=157,
  serialized_end=247,
)

_sym_db.RegisterEnumDescriptor(_SEARCHREQUEST_CORPUS)   ## 系统文件.描述枚举类型
## 枚举类型  所有成员的 结束   是指是一个元组

## 下面是描述成员字段

_SEARCHREQUEST = _descriptor.Descriptor(  ##SEACHERQUEST  就是消息类型的类名  描述符.描述
  name='SearchRequest',## 文件名
  full_name='SearchRequest', ##
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[   ## 文件的成员
    _descriptor.FieldDescriptor(
      name='query', full_name='SearchRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='page_number', full_name='SearchRequest.page_number', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result_per_page', full_name='SearchRequest.result_per_page', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=10,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='corpus', full_name='SearchRequest.corpus', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SEARCHREQUEST_CORPUS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=247,
)

_SEARCHREQUEST.fields_by_name['corpus'].enum_type = _SEARCHREQUEST_CORPUS
_SEARCHREQUEST_CORPUS.containing_type = _SEARCHREQUEST
DESCRIPTOR.message_types_by_name['SearchRequest'] = _SEARCHREQUEST

SearchRequest = _reflection.GeneratedProtocolMessageType('SearchRequest', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHREQUEST,
  __module__ = 'protobuf_test.temp2_pb2'
  # @@protoc_insertion_point(class_scope:SearchRequest)
  ))   ## 这个或许就是类名  或许就是类名  或许就是类名
_sym_db.RegisterMessage(SearchRequest)


# @@protoc_insertion_point(module_scope)
