# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf_test/user.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()



# 表示当前protobuf 的文件路劲
DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf_test/user.proto',
  package='',
  serialized_pb=_b('\n\x13protobuf/user.proto\"\x83\x01\n\x07userIfo\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0f\n\x03\x61ge\x18\x02 \x02(\x05:\x02\x32\x30\x12&\n\x05habby\x18\x03 \x01(\x0e\x32\x0f.userIfo.Habbys:\x06zhuqiu\"1\n\x06Habbys\x12\x0c\n\x08\x62\x61skball\x10\x00\x12\r\n\tping_pang\x10\x01\x12\n\n\x06zhuqiu\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

# 表示枚举  转化后表示生成的代码是这一部分
_USERIFO_HABBYS = _descriptor.EnumDescriptor(
  name='Habbys',
  full_name='userIfo.Habbys',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='baskball', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ping_pang', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='zhuqiu', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=106,
  serialized_end=155,
)
_sym_db.RegisterEnumDescriptor(_USERIFO_HABBYS)

# 每个字段  转化后每个字段生成的代码是这一部分
_USERIFO = _descriptor.Descriptor(
  name='userIfo',
  full_name='userIfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='userIfo.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='age', full_name='userIfo.age', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=20,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='habby', full_name='userIfo.habby', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _USERIFO_HABBYS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=155,
)

_USERIFO.fields_by_name['habby'].enum_type = _USERIFO_HABBYS
_USERIFO_HABBYS.containing_type = _USERIFO
DESCRIPTOR.message_types_by_name['userIfo'] = _USERIFO

userIfo = _reflection.GeneratedProtocolMessageType('userIfo', (_message.Message,), dict(
  DESCRIPTOR = _USERIFO,
  __module__ = 'protobuf_test.user_pb2'
  # @@protoc_insertion_point(class_scope:userIfo)
  ))
_sym_db.RegisterMessage(userIfo)


# @@protoc_insertion_point(module_scope)
