# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: baopai.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pai_pb2 as pai__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='baopai.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0c\x62\x61opai.proto\x1a\tpai.proto\"9\n\x10\x42\x61oPaiShowNotify\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x14\n\x06\x62\x61opai\x18\x02 \x02(\x0b\x32\x04.Pai\";\n\x12\x42\x61oPaiChangeNotify\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x14\n\x06newBao\x18\x02 \x02(\x0b\x32\x04.Pai')
  ,
  dependencies=[pai__pb2.DESCRIPTOR,])




_BAOPAISHOWNOTIFY = _descriptor.Descriptor(
  name='BaoPaiShowNotify',
  full_name='BaoPaiShowNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='BaoPaiShowNotify.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='baopai', full_name='BaoPaiShowNotify.baopai', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=84,
)


_BAOPAICHANGENOTIFY = _descriptor.Descriptor(
  name='BaoPaiChangeNotify',
  full_name='BaoPaiChangeNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='BaoPaiChangeNotify.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='newBao', full_name='BaoPaiChangeNotify.newBao', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=145,
)

_BAOPAISHOWNOTIFY.fields_by_name['baopai'].message_type = pai__pb2._PAI
_BAOPAICHANGENOTIFY.fields_by_name['newBao'].message_type = pai__pb2._PAI
DESCRIPTOR.message_types_by_name['BaoPaiShowNotify'] = _BAOPAISHOWNOTIFY
DESCRIPTOR.message_types_by_name['BaoPaiChangeNotify'] = _BAOPAICHANGENOTIFY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BaoPaiShowNotify = _reflection.GeneratedProtocolMessageType('BaoPaiShowNotify', (_message.Message,), dict(
  DESCRIPTOR = _BAOPAISHOWNOTIFY,
  __module__ = 'baopai_pb2'
  # @@protoc_insertion_point(class_scope:BaoPaiShowNotify)
  ))
_sym_db.RegisterMessage(BaoPaiShowNotify)

BaoPaiChangeNotify = _reflection.GeneratedProtocolMessageType('BaoPaiChangeNotify', (_message.Message,), dict(
  DESCRIPTOR = _BAOPAICHANGENOTIFY,
  __module__ = 'baopai_pb2'
  # @@protoc_insertion_point(class_scope:BaoPaiChangeNotify)
  ))
_sym_db.RegisterMessage(BaoPaiChangeNotify)


# @@protoc_insertion_point(module_scope)
