# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: broadcast.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='broadcast.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0f\x62roadcast.proto\"H\n\tBroadCast\x12\x0b\n\x03nID\x18\x01 \x02(\x05\x12\x0e\n\x06sTitle\x18\x02 \x02(\t\x12\x0f\n\x07sDetail\x18\x03 \x02(\t\x12\r\n\x05sDate\x18\x04 \x02(\t\"#\n\x10\x42roadCastRequest\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\"B\n\x11\x42roadCastResponse\x12\x12\n\nnErrorCode\x18\x01 \x02(\x05\x12\x19\n\x05\x62Pool\x18\x02 \x03(\x0b\x32\n.BroadCast')
)




_BROADCAST = _descriptor.Descriptor(
  name='BroadCast',
  full_name='BroadCast',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nID', full_name='BroadCast.nID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sTitle', full_name='BroadCast.sTitle', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sDetail', full_name='BroadCast.sDetail', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sDate', full_name='BroadCast.sDate', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=91,
)


_BROADCASTREQUEST = _descriptor.Descriptor(
  name='BroadCastRequest',
  full_name='BroadCastRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='BroadCastRequest.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=128,
)


_BROADCASTRESPONSE = _descriptor.Descriptor(
  name='BroadCastResponse',
  full_name='BroadCastResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nErrorCode', full_name='BroadCastResponse.nErrorCode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bPool', full_name='BroadCastResponse.bPool', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=196,
)

_BROADCASTRESPONSE.fields_by_name['bPool'].message_type = _BROADCAST
DESCRIPTOR.message_types_by_name['BroadCast'] = _BROADCAST
DESCRIPTOR.message_types_by_name['BroadCastRequest'] = _BROADCASTREQUEST
DESCRIPTOR.message_types_by_name['BroadCastResponse'] = _BROADCASTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BroadCast = _reflection.GeneratedProtocolMessageType('BroadCast', (_message.Message,), dict(
  DESCRIPTOR = _BROADCAST,
  __module__ = 'broadcast_pb2'
  # @@protoc_insertion_point(class_scope:BroadCast)
  ))
_sym_db.RegisterMessage(BroadCast)

BroadCastRequest = _reflection.GeneratedProtocolMessageType('BroadCastRequest', (_message.Message,), dict(
  DESCRIPTOR = _BROADCASTREQUEST,
  __module__ = 'broadcast_pb2'
  # @@protoc_insertion_point(class_scope:BroadCastRequest)
  ))
_sym_db.RegisterMessage(BroadCastRequest)

BroadCastResponse = _reflection.GeneratedProtocolMessageType('BroadCastResponse', (_message.Message,), dict(
  DESCRIPTOR = _BROADCASTRESPONSE,
  __module__ = 'broadcast_pb2'
  # @@protoc_insertion_point(class_scope:BroadCastResponse)
  ))
_sym_db.RegisterMessage(BroadCastResponse)


# @@protoc_insertion_point(module_scope)
