# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: can_pai.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pai_pb2 as pai__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='can_pai.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\rcan_pai.proto\x1a\tpai.proto\"\x96\x02\n\x0c\x43\x61nPaiNotify\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x15\n\x07lastPai\x18\x02 \x01(\x0b\x32\x04.Pai\x12\x0f\n\x07\x63\x61nTing\x18\x03 \x01(\x08\x12\r\n\x05\x63\x61nHu\x18\x04 \x01(\x08\x12\x14\n\x0c\x63\x61nQiangTing\x18\x05 \x01(\x08\x12\x0f\n\x07\x63\x61nGang\x18\x06 \x01(\x08\x12\x0f\n\x07\x63\x61nPeng\x18\x07 \x01(\x08\x12\x0e\n\x06\x63\x61nChi\x18\x08 \x01(\x08\x12\x1b\n\ncanChiPool\x18\t \x03(\x0b\x32\x07.ChiPai\x12\x19\n\x0b\x63\x61nPengPool\x18\n \x03(\x0b\x32\x04.Pai\x12\x1d\n\x0b\x63\x61nGangPool\x18\x0b \x03(\x0b\x32\x08.GangPai\x12\x12\n\nlastHuType\x18\x0c \x01(\x05\x12\x0b\n\x03\x62Zm\x18\r \x01(\x08')
  ,
  dependencies=[pai__pb2.DESCRIPTOR,])




_CANPAINOTIFY = _descriptor.Descriptor(
  name='CanPaiNotify',
  full_name='CanPaiNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='CanPaiNotify.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastPai', full_name='CanPaiNotify.lastPai', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='canTing', full_name='CanPaiNotify.canTing', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='canHu', full_name='CanPaiNotify.canHu', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='canQiangTing', full_name='CanPaiNotify.canQiangTing', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='canGang', full_name='CanPaiNotify.canGang', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='canPeng', full_name='CanPaiNotify.canPeng', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='canChi', full_name='CanPaiNotify.canChi', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='canChiPool', full_name='CanPaiNotify.canChiPool', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='canPengPool', full_name='CanPaiNotify.canPengPool', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='canGangPool', full_name='CanPaiNotify.canGangPool', index=10,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastHuType', full_name='CanPaiNotify.lastHuType', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bZm', full_name='CanPaiNotify.bZm', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=307,
)

_CANPAINOTIFY.fields_by_name['lastPai'].message_type = pai__pb2._PAI
_CANPAINOTIFY.fields_by_name['canChiPool'].message_type = pai__pb2._CHIPAI
_CANPAINOTIFY.fields_by_name['canPengPool'].message_type = pai__pb2._PAI
_CANPAINOTIFY.fields_by_name['canGangPool'].message_type = pai__pb2._GANGPAI
DESCRIPTOR.message_types_by_name['CanPaiNotify'] = _CANPAINOTIFY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CanPaiNotify = _reflection.GeneratedProtocolMessageType('CanPaiNotify', (_message.Message,), dict(
  DESCRIPTOR = _CANPAINOTIFY,
  __module__ = 'can_pai_pb2'
  # @@protoc_insertion_point(class_scope:CanPaiNotify)
  ))
_sym_db.RegisterMessage(CanPaiNotify)


# @@protoc_insertion_point(module_scope)
