# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: create_room.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gameplay_pb2 as gameplay__pb2
import assets_pb2 as assets__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='create_room.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x11\x63reate_room.proto\x1a\x0egameplay.proto\x1a\x0c\x61ssets.proto\"f\n\x11\x43reateRoomRequest\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x11\n\tsCardType\x18\x02 \x02(\t\x12\x1b\n\x08gamePlay\x18\x03 \x02(\x0b\x32\t.GamePlay\x12\x10\n\x08nPlayers\x18\x04 \x02(\x05\"\x9c\x01\n\x12\x43reateRoomResponse\x12\x12\n\nnErrorCode\x18\x01 \x02(\x05\x12\x0f\n\x07sRoomID\x18\x02 \x01(\t\x12\x11\n\tsCardType\x18\x03 \x01(\t\x12\x1b\n\x08gamePlay\x18\x04 \x01(\x0b\x32\t.GamePlay\x12\x10\n\x08nPlayers\x18\x05 \x01(\x05\x12\x1f\n\tnewAssets\x18\x06 \x01(\x0b\x32\x0c.AssetUpdate')
  ,
  dependencies=[gameplay__pb2.DESCRIPTOR,assets__pb2.DESCRIPTOR,])




_CREATEROOMREQUEST = _descriptor.Descriptor(
  name='CreateRoomRequest',
  full_name='CreateRoomRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='CreateRoomRequest.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sCardType', full_name='CreateRoomRequest.sCardType', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gamePlay', full_name='CreateRoomRequest.gamePlay', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nPlayers', full_name='CreateRoomRequest.nPlayers', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=153,
)


_CREATEROOMRESPONSE = _descriptor.Descriptor(
  name='CreateRoomResponse',
  full_name='CreateRoomResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nErrorCode', full_name='CreateRoomResponse.nErrorCode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='CreateRoomResponse.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sCardType', full_name='CreateRoomResponse.sCardType', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gamePlay', full_name='CreateRoomResponse.gamePlay', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nPlayers', full_name='CreateRoomResponse.nPlayers', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='newAssets', full_name='CreateRoomResponse.newAssets', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=312,
)

_CREATEROOMREQUEST.fields_by_name['gamePlay'].message_type = gameplay__pb2._GAMEPLAY
_CREATEROOMRESPONSE.fields_by_name['gamePlay'].message_type = gameplay__pb2._GAMEPLAY
_CREATEROOMRESPONSE.fields_by_name['newAssets'].message_type = assets__pb2._ASSETUPDATE
DESCRIPTOR.message_types_by_name['CreateRoomRequest'] = _CREATEROOMREQUEST
DESCRIPTOR.message_types_by_name['CreateRoomResponse'] = _CREATEROOMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateRoomRequest = _reflection.GeneratedProtocolMessageType('CreateRoomRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATEROOMREQUEST,
  __module__ = 'create_room_pb2'
  # @@protoc_insertion_point(class_scope:CreateRoomRequest)
  ))
_sym_db.RegisterMessage(CreateRoomRequest)

CreateRoomResponse = _reflection.GeneratedProtocolMessageType('CreateRoomResponse', (_message.Message,), dict(
  DESCRIPTOR = _CREATEROOMRESPONSE,
  __module__ = 'create_room_pb2'
  # @@protoc_insertion_point(class_scope:CreateRoomResponse)
  ))
_sym_db.RegisterMessage(CreateRoomResponse)


# @@protoc_insertion_point(module_scope)
