# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: delegate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='delegate.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0e\x64\x65legate.proto\"@\n\x0f\x44\x65legateRequest\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x0f\n\x07sRoomID\x18\x02 \x02(\t\x12\x0b\n\x03\x62\x44o\x18\x03 \x01(\x08\"3\n\x10\x44\x65legateResponse\x12\x12\n\nnErrorCode\x18\x01 \x02(\x05\x12\x0b\n\x03\x62\x44o\x18\x02 \x01(\x08\"!\n\x0e\x44\x65legateNotify\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05')
)




_DELEGATEREQUEST = _descriptor.Descriptor(
  name='DelegateRequest',
  full_name='DelegateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='DelegateRequest.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='DelegateRequest.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bDo', full_name='DelegateRequest.bDo', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=82,
)


_DELEGATERESPONSE = _descriptor.Descriptor(
  name='DelegateResponse',
  full_name='DelegateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nErrorCode', full_name='DelegateResponse.nErrorCode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bDo', full_name='DelegateResponse.bDo', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=135,
)


_DELEGATENOTIFY = _descriptor.Descriptor(
  name='DelegateNotify',
  full_name='DelegateNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='DelegateNotify.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=170,
)

DESCRIPTOR.message_types_by_name['DelegateRequest'] = _DELEGATEREQUEST
DESCRIPTOR.message_types_by_name['DelegateResponse'] = _DELEGATERESPONSE
DESCRIPTOR.message_types_by_name['DelegateNotify'] = _DELEGATENOTIFY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DelegateRequest = _reflection.GeneratedProtocolMessageType('DelegateRequest', (_message.Message,), dict(
  DESCRIPTOR = _DELEGATEREQUEST,
  __module__ = 'delegate_pb2'
  # @@protoc_insertion_point(class_scope:DelegateRequest)
  ))
_sym_db.RegisterMessage(DelegateRequest)

DelegateResponse = _reflection.GeneratedProtocolMessageType('DelegateResponse', (_message.Message,), dict(
  DESCRIPTOR = _DELEGATERESPONSE,
  __module__ = 'delegate_pb2'
  # @@protoc_insertion_point(class_scope:DelegateResponse)
  ))
_sym_db.RegisterMessage(DelegateResponse)

DelegateNotify = _reflection.GeneratedProtocolMessageType('DelegateNotify', (_message.Message,), dict(
  DESCRIPTOR = _DELEGATENOTIFY,
  __module__ = 'delegate_pb2'
  # @@protoc_insertion_point(class_scope:DelegateNotify)
  ))
_sym_db.RegisterMessage(DelegateNotify)


# @@protoc_insertion_point(module_scope)
