# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: diss_room.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='diss_room.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0f\x64iss_room.proto\"3\n\x0f\x44issRoomRequest\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x0f\n\x07sRoomID\x18\x02 \x02(\t\"&\n\x10\x44issRoomResponse\x12\x12\n\nnErrorCode\x18\x01 \x02(\x05\"2\n\x0e\x44issRoomNotify\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x0f\n\x07sRoomID\x18\x02 \x02(\t')
)




_DISSROOMREQUEST = _descriptor.Descriptor(
  name='DissRoomRequest',
  full_name='DissRoomRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='DissRoomRequest.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='DissRoomRequest.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=70,
)


_DISSROOMRESPONSE = _descriptor.Descriptor(
  name='DissRoomResponse',
  full_name='DissRoomResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nErrorCode', full_name='DissRoomResponse.nErrorCode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=110,
)


_DISSROOMNOTIFY = _descriptor.Descriptor(
  name='DissRoomNotify',
  full_name='DissRoomNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='DissRoomNotify.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='DissRoomNotify.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=162,
)

DESCRIPTOR.message_types_by_name['DissRoomRequest'] = _DISSROOMREQUEST
DESCRIPTOR.message_types_by_name['DissRoomResponse'] = _DISSROOMRESPONSE
DESCRIPTOR.message_types_by_name['DissRoomNotify'] = _DISSROOMNOTIFY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DissRoomRequest = _reflection.GeneratedProtocolMessageType('DissRoomRequest', (_message.Message,), dict(
  DESCRIPTOR = _DISSROOMREQUEST,
  __module__ = 'diss_room_pb2'
  # @@protoc_insertion_point(class_scope:DissRoomRequest)
  ))
_sym_db.RegisterMessage(DissRoomRequest)

DissRoomResponse = _reflection.GeneratedProtocolMessageType('DissRoomResponse', (_message.Message,), dict(
  DESCRIPTOR = _DISSROOMRESPONSE,
  __module__ = 'diss_room_pb2'
  # @@protoc_insertion_point(class_scope:DissRoomResponse)
  ))
_sym_db.RegisterMessage(DissRoomResponse)

DissRoomNotify = _reflection.GeneratedProtocolMessageType('DissRoomNotify', (_message.Message,), dict(
  DESCRIPTOR = _DISSROOMNOTIFY,
  __module__ = 'diss_room_pb2'
  # @@protoc_insertion_point(class_scope:DissRoomNotify)
  ))
_sym_db.RegisterMessage(DissRoomNotify)


# @@protoc_insertion_point(module_scope)
