# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: do_chi_pai.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pai_pb2 as pai__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='do_chi_pai.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x10\x64o_chi_pai.proto\x1a\tpai.proto\"Y\n\x0f\x44oChiPaiRequest\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x0f\n\x07sRoomID\x18\x02 \x02(\t\x12\x11\n\x03pai\x18\x03 \x02(\x0b\x32\x04.Pai\x12\x11\n\tnChiIndex\x18\x04 \x02(\x05\"w\n\x10\x44oChiPaiResponse\x12\x12\n\nnErrorCode\x18\x01 \x02(\x05\x12\x0f\n\x07nLastID\x18\x02 \x02(\x05\x12\x15\n\x07lastPai\x18\x03 \x02(\x0b\x32\x04.Pai\x12\x11\n\tnChiIndex\x18\x04 \x02(\x05\x12\x14\n\x03pai\x18\x05 \x02(\x0b\x32\x07.ChiPai\"p\n\x0e\x44oChiPaiNotify\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x0f\n\x07sRoomID\x18\x02 \x02(\t\x12\x14\n\x03pai\x18\x03 \x02(\x0b\x32\x07.ChiPai\x12\x0f\n\x07nLastID\x18\x04 \x02(\x05\x12\x15\n\x07lastPai\x18\x05 \x02(\x0b\x32\x04.Pai')
  ,
  dependencies=[pai__pb2.DESCRIPTOR,])




_DOCHIPAIREQUEST = _descriptor.Descriptor(
  name='DoChiPaiRequest',
  full_name='DoChiPaiRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='DoChiPaiRequest.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='DoChiPaiRequest.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pai', full_name='DoChiPaiRequest.pai', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nChiIndex', full_name='DoChiPaiRequest.nChiIndex', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=120,
)


_DOCHIPAIRESPONSE = _descriptor.Descriptor(
  name='DoChiPaiResponse',
  full_name='DoChiPaiResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nErrorCode', full_name='DoChiPaiResponse.nErrorCode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nLastID', full_name='DoChiPaiResponse.nLastID', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastPai', full_name='DoChiPaiResponse.lastPai', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nChiIndex', full_name='DoChiPaiResponse.nChiIndex', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pai', full_name='DoChiPaiResponse.pai', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=241,
)


_DOCHIPAINOTIFY = _descriptor.Descriptor(
  name='DoChiPaiNotify',
  full_name='DoChiPaiNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='DoChiPaiNotify.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='DoChiPaiNotify.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pai', full_name='DoChiPaiNotify.pai', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nLastID', full_name='DoChiPaiNotify.nLastID', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastPai', full_name='DoChiPaiNotify.lastPai', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=355,
)

_DOCHIPAIREQUEST.fields_by_name['pai'].message_type = pai__pb2._PAI
_DOCHIPAIRESPONSE.fields_by_name['lastPai'].message_type = pai__pb2._PAI
_DOCHIPAIRESPONSE.fields_by_name['pai'].message_type = pai__pb2._CHIPAI
_DOCHIPAINOTIFY.fields_by_name['pai'].message_type = pai__pb2._CHIPAI
_DOCHIPAINOTIFY.fields_by_name['lastPai'].message_type = pai__pb2._PAI
DESCRIPTOR.message_types_by_name['DoChiPaiRequest'] = _DOCHIPAIREQUEST
DESCRIPTOR.message_types_by_name['DoChiPaiResponse'] = _DOCHIPAIRESPONSE
DESCRIPTOR.message_types_by_name['DoChiPaiNotify'] = _DOCHIPAINOTIFY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DoChiPaiRequest = _reflection.GeneratedProtocolMessageType('DoChiPaiRequest', (_message.Message,), dict(
  DESCRIPTOR = _DOCHIPAIREQUEST,
  __module__ = 'do_chi_pai_pb2'
  # @@protoc_insertion_point(class_scope:DoChiPaiRequest)
  ))
_sym_db.RegisterMessage(DoChiPaiRequest)

DoChiPaiResponse = _reflection.GeneratedProtocolMessageType('DoChiPaiResponse', (_message.Message,), dict(
  DESCRIPTOR = _DOCHIPAIRESPONSE,
  __module__ = 'do_chi_pai_pb2'
  # @@protoc_insertion_point(class_scope:DoChiPaiResponse)
  ))
_sym_db.RegisterMessage(DoChiPaiResponse)

DoChiPaiNotify = _reflection.GeneratedProtocolMessageType('DoChiPaiNotify', (_message.Message,), dict(
  DESCRIPTOR = _DOCHIPAINOTIFY,
  __module__ = 'do_chi_pai_pb2'
  # @@protoc_insertion_point(class_scope:DoChiPaiNotify)
  ))
_sym_db.RegisterMessage(DoChiPaiNotify)


# @@protoc_insertion_point(module_scope)
