# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: do_gang_pai.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pai_pb2 as pai__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='do_gang_pai.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x11\x64o_gang_pai.proto\x1a\tpai.proto\"K\n\x10\x44oGangPaiRequest\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x0f\n\x07sRoomID\x18\x02 \x02(\t\x12\x15\n\x03pai\x18\x03 \x02(\x0b\x32\x08.GangPai\"f\n\x11\x44oGangPaiResponse\x12\x12\n\nnErrorCode\x18\x01 \x02(\x05\x12\x0f\n\x07nLastID\x18\x02 \x01(\x05\x12\x15\n\x07lastPai\x18\x03 \x01(\x0b\x32\x04.Pai\x12\x15\n\x03pai\x18\x04 \x01(\x0b\x32\x08.GangPai\"r\n\x0f\x44oGangPaiNotify\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x0f\n\x07sRoomID\x18\x02 \x02(\t\x12\x15\n\x03pai\x18\x03 \x02(\x0b\x32\x08.GangPai\x12\x0f\n\x07nLastID\x18\x04 \x01(\x05\x12\x15\n\x07lastPai\x18\x05 \x01(\x0b\x32\x04.Pai')
  ,
  dependencies=[pai__pb2.DESCRIPTOR,])




_DOGANGPAIREQUEST = _descriptor.Descriptor(
  name='DoGangPaiRequest',
  full_name='DoGangPaiRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='DoGangPaiRequest.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='DoGangPaiRequest.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pai', full_name='DoGangPaiRequest.pai', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=107,
)


_DOGANGPAIRESPONSE = _descriptor.Descriptor(
  name='DoGangPaiResponse',
  full_name='DoGangPaiResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nErrorCode', full_name='DoGangPaiResponse.nErrorCode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nLastID', full_name='DoGangPaiResponse.nLastID', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastPai', full_name='DoGangPaiResponse.lastPai', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pai', full_name='DoGangPaiResponse.pai', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=211,
)


_DOGANGPAINOTIFY = _descriptor.Descriptor(
  name='DoGangPaiNotify',
  full_name='DoGangPaiNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='DoGangPaiNotify.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='DoGangPaiNotify.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pai', full_name='DoGangPaiNotify.pai', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nLastID', full_name='DoGangPaiNotify.nLastID', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastPai', full_name='DoGangPaiNotify.lastPai', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=327,
)

_DOGANGPAIREQUEST.fields_by_name['pai'].message_type = pai__pb2._GANGPAI
_DOGANGPAIRESPONSE.fields_by_name['lastPai'].message_type = pai__pb2._PAI
_DOGANGPAIRESPONSE.fields_by_name['pai'].message_type = pai__pb2._GANGPAI
_DOGANGPAINOTIFY.fields_by_name['pai'].message_type = pai__pb2._GANGPAI
_DOGANGPAINOTIFY.fields_by_name['lastPai'].message_type = pai__pb2._PAI
DESCRIPTOR.message_types_by_name['DoGangPaiRequest'] = _DOGANGPAIREQUEST
DESCRIPTOR.message_types_by_name['DoGangPaiResponse'] = _DOGANGPAIRESPONSE
DESCRIPTOR.message_types_by_name['DoGangPaiNotify'] = _DOGANGPAINOTIFY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DoGangPaiRequest = _reflection.GeneratedProtocolMessageType('DoGangPaiRequest', (_message.Message,), dict(
  DESCRIPTOR = _DOGANGPAIREQUEST,
  __module__ = 'do_gang_pai_pb2'
  # @@protoc_insertion_point(class_scope:DoGangPaiRequest)
  ))
_sym_db.RegisterMessage(DoGangPaiRequest)

DoGangPaiResponse = _reflection.GeneratedProtocolMessageType('DoGangPaiResponse', (_message.Message,), dict(
  DESCRIPTOR = _DOGANGPAIRESPONSE,
  __module__ = 'do_gang_pai_pb2'
  # @@protoc_insertion_point(class_scope:DoGangPaiResponse)
  ))
_sym_db.RegisterMessage(DoGangPaiResponse)

DoGangPaiNotify = _reflection.GeneratedProtocolMessageType('DoGangPaiNotify', (_message.Message,), dict(
  DESCRIPTOR = _DOGANGPAINOTIFY,
  __module__ = 'do_gang_pai_pb2'
  # @@protoc_insertion_point(class_scope:DoGangPaiNotify)
  ))
_sym_db.RegisterMessage(DoGangPaiNotify)


# @@protoc_insertion_point(module_scope)
