# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: do_hu_pai.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pai_pb2 as pai__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='do_hu_pai.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0f\x64o_hu_pai.proto\x1a\tpai.proto\"E\n\x0e\x44oHuPaiRequest\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x0f\n\x07sRoomID\x18\x02 \x02(\t\x12\x11\n\x03pai\x18\x03 \x02(\x0b\x32\x04.Pai\"%\n\x0f\x44oHuPaiResponse\x12\x12\n\nnErrorCode\x18\x01 \x02(\x05\"D\n\rDoHuPaiNotify\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x0f\n\x07sRoomID\x18\x02 \x02(\t\x12\x11\n\x03pai\x18\x03 \x02(\x0b\x32\x04.Pai')
  ,
  dependencies=[pai__pb2.DESCRIPTOR,])




_DOHUPAIREQUEST = _descriptor.Descriptor(
  name='DoHuPaiRequest',
  full_name='DoHuPaiRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='DoHuPaiRequest.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='DoHuPaiRequest.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pai', full_name='DoHuPaiRequest.pai', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=99,
)


_DOHUPAIRESPONSE = _descriptor.Descriptor(
  name='DoHuPaiResponse',
  full_name='DoHuPaiResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nErrorCode', full_name='DoHuPaiResponse.nErrorCode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=138,
)


_DOHUPAINOTIFY = _descriptor.Descriptor(
  name='DoHuPaiNotify',
  full_name='DoHuPaiNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='DoHuPaiNotify.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='DoHuPaiNotify.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pai', full_name='DoHuPaiNotify.pai', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=208,
)

_DOHUPAIREQUEST.fields_by_name['pai'].message_type = pai__pb2._PAI
_DOHUPAINOTIFY.fields_by_name['pai'].message_type = pai__pb2._PAI
DESCRIPTOR.message_types_by_name['DoHuPaiRequest'] = _DOHUPAIREQUEST
DESCRIPTOR.message_types_by_name['DoHuPaiResponse'] = _DOHUPAIRESPONSE
DESCRIPTOR.message_types_by_name['DoHuPaiNotify'] = _DOHUPAINOTIFY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DoHuPaiRequest = _reflection.GeneratedProtocolMessageType('DoHuPaiRequest', (_message.Message,), dict(
  DESCRIPTOR = _DOHUPAIREQUEST,
  __module__ = 'do_hu_pai_pb2'
  # @@protoc_insertion_point(class_scope:DoHuPaiRequest)
  ))
_sym_db.RegisterMessage(DoHuPaiRequest)

DoHuPaiResponse = _reflection.GeneratedProtocolMessageType('DoHuPaiResponse', (_message.Message,), dict(
  DESCRIPTOR = _DOHUPAIRESPONSE,
  __module__ = 'do_hu_pai_pb2'
  # @@protoc_insertion_point(class_scope:DoHuPaiResponse)
  ))
_sym_db.RegisterMessage(DoHuPaiResponse)

DoHuPaiNotify = _reflection.GeneratedProtocolMessageType('DoHuPaiNotify', (_message.Message,), dict(
  DESCRIPTOR = _DOHUPAINOTIFY,
  __module__ = 'do_hu_pai_pb2'
  # @@protoc_insertion_point(class_scope:DoHuPaiNotify)
  ))
_sym_db.RegisterMessage(DoHuPaiNotify)


# @@protoc_insertion_point(module_scope)
