# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: do_peng_pai.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pai_pb2 as pai__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='do_peng_pai.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x11\x64o_peng_pai.proto\x1a\tpai.proto\"G\n\x10\x44oPengPaiRequest\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x0f\n\x07sRoomID\x18\x02 \x02(\t\x12\x11\n\x03pai\x18\x03 \x02(\x0b\x32\x04.Pai\"O\n\x11\x44oPengPaiResponse\x12\x12\n\nnErrorCode\x18\x01 \x02(\x05\x12\x0f\n\x07nLastID\x18\x02 \x02(\x05\x12\x15\n\x07lastPai\x18\x03 \x02(\x0b\x32\x04.Pai\"n\n\x0f\x44oPengPaiNotify\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x0f\n\x07sRoomID\x18\x02 \x02(\t\x12\x11\n\x03pai\x18\x03 \x02(\x0b\x32\x04.Pai\x12\x0f\n\x07nLastID\x18\x04 \x02(\x05\x12\x15\n\x07lastPai\x18\x05 \x02(\x0b\x32\x04.Pai')
  ,
  dependencies=[pai__pb2.DESCRIPTOR,])




_DOPENGPAIREQUEST = _descriptor.Descriptor(
  name='DoPengPaiRequest',
  full_name='DoPengPaiRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='DoPengPaiRequest.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='DoPengPaiRequest.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pai', full_name='DoPengPaiRequest.pai', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=103,
)


_DOPENGPAIRESPONSE = _descriptor.Descriptor(
  name='DoPengPaiResponse',
  full_name='DoPengPaiResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nErrorCode', full_name='DoPengPaiResponse.nErrorCode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nLastID', full_name='DoPengPaiResponse.nLastID', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastPai', full_name='DoPengPaiResponse.lastPai', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=184,
)


_DOPENGPAINOTIFY = _descriptor.Descriptor(
  name='DoPengPaiNotify',
  full_name='DoPengPaiNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='DoPengPaiNotify.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='DoPengPaiNotify.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pai', full_name='DoPengPaiNotify.pai', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nLastID', full_name='DoPengPaiNotify.nLastID', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastPai', full_name='DoPengPaiNotify.lastPai', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=296,
)

_DOPENGPAIREQUEST.fields_by_name['pai'].message_type = pai__pb2._PAI
_DOPENGPAIRESPONSE.fields_by_name['lastPai'].message_type = pai__pb2._PAI
_DOPENGPAINOTIFY.fields_by_name['pai'].message_type = pai__pb2._PAI
_DOPENGPAINOTIFY.fields_by_name['lastPai'].message_type = pai__pb2._PAI
DESCRIPTOR.message_types_by_name['DoPengPaiRequest'] = _DOPENGPAIREQUEST
DESCRIPTOR.message_types_by_name['DoPengPaiResponse'] = _DOPENGPAIRESPONSE
DESCRIPTOR.message_types_by_name['DoPengPaiNotify'] = _DOPENGPAINOTIFY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DoPengPaiRequest = _reflection.GeneratedProtocolMessageType('DoPengPaiRequest', (_message.Message,), dict(
  DESCRIPTOR = _DOPENGPAIREQUEST,
  __module__ = 'do_peng_pai_pb2'
  # @@protoc_insertion_point(class_scope:DoPengPaiRequest)
  ))
_sym_db.RegisterMessage(DoPengPaiRequest)

DoPengPaiResponse = _reflection.GeneratedProtocolMessageType('DoPengPaiResponse', (_message.Message,), dict(
  DESCRIPTOR = _DOPENGPAIRESPONSE,
  __module__ = 'do_peng_pai_pb2'
  # @@protoc_insertion_point(class_scope:DoPengPaiResponse)
  ))
_sym_db.RegisterMessage(DoPengPaiResponse)

DoPengPaiNotify = _reflection.GeneratedProtocolMessageType('DoPengPaiNotify', (_message.Message,), dict(
  DESCRIPTOR = _DOPENGPAINOTIFY,
  __module__ = 'do_peng_pai_pb2'
  # @@protoc_insertion_point(class_scope:DoPengPaiNotify)
  ))
_sym_db.RegisterMessage(DoPengPaiNotify)


# @@protoc_insertion_point(module_scope)
