# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: do_qiang_ting_pai.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pai_pb2 as pai__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='do_qiang_ting_pai.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x17\x64o_qiang_ting_pai.proto\x1a\tpai.proto\"_\n\x15\x44oQiangTingPaiRequest\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x0f\n\x07sRoomID\x18\x02 \x02(\t\x12\x11\n\x03pai\x18\x03 \x02(\x0b\x32\x04.Pai\x12\x11\n\tnChiIndex\x18\x04 \x02(\x05\"\xaa\x01\n\x16\x44oQiangTingPaiResponse\x12\x12\n\nnErrorCode\x18\x01 \x02(\x05\x12\x11\n\tnChiIndex\x18\x02 \x01(\x05\x12\x0f\n\x07nLastID\x18\x03 \x02(\x05\x12\x15\n\x07lastPai\x18\x04 \x02(\x0b\x32\x04.Pai\x12\x11\n\x03pai\x18\x05 \x02(\x0b\x32\x04.Pai\x12\x17\n\x06\x63hipai\x18\x06 \x01(\x0b\x32\x07.ChiPai\x12\x15\n\x07pengpai\x18\x07 \x01(\x0b\x32\x04.Pai\"\xa3\x01\n\x14\x44oQiangTingPaiNotify\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x0f\n\x07sRoomID\x18\x02 \x02(\t\x12\x11\n\x03pai\x18\x03 \x02(\x0b\x32\x04.Pai\x12\x17\n\x06\x63hipai\x18\x04 \x01(\x0b\x32\x07.ChiPai\x12\x15\n\x07pengpai\x18\x05 \x01(\x0b\x32\x04.Pai\x12\x0f\n\x07nLastID\x18\x06 \x02(\x05\x12\x15\n\x07lastPai\x18\x07 \x02(\x0b\x32\x04.Pai')
  ,
  dependencies=[pai__pb2.DESCRIPTOR,])




_DOQIANGTINGPAIREQUEST = _descriptor.Descriptor(
  name='DoQiangTingPaiRequest',
  full_name='DoQiangTingPaiRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='DoQiangTingPaiRequest.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='DoQiangTingPaiRequest.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pai', full_name='DoQiangTingPaiRequest.pai', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nChiIndex', full_name='DoQiangTingPaiRequest.nChiIndex', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=133,
)


_DOQIANGTINGPAIRESPONSE = _descriptor.Descriptor(
  name='DoQiangTingPaiResponse',
  full_name='DoQiangTingPaiResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nErrorCode', full_name='DoQiangTingPaiResponse.nErrorCode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nChiIndex', full_name='DoQiangTingPaiResponse.nChiIndex', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nLastID', full_name='DoQiangTingPaiResponse.nLastID', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastPai', full_name='DoQiangTingPaiResponse.lastPai', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pai', full_name='DoQiangTingPaiResponse.pai', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chipai', full_name='DoQiangTingPaiResponse.chipai', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pengpai', full_name='DoQiangTingPaiResponse.pengpai', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=306,
)


_DOQIANGTINGPAINOTIFY = _descriptor.Descriptor(
  name='DoQiangTingPaiNotify',
  full_name='DoQiangTingPaiNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='DoQiangTingPaiNotify.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='DoQiangTingPaiNotify.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pai', full_name='DoQiangTingPaiNotify.pai', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chipai', full_name='DoQiangTingPaiNotify.chipai', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pengpai', full_name='DoQiangTingPaiNotify.pengpai', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nLastID', full_name='DoQiangTingPaiNotify.nLastID', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastPai', full_name='DoQiangTingPaiNotify.lastPai', index=6,
      number=7, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=472,
)

_DOQIANGTINGPAIREQUEST.fields_by_name['pai'].message_type = pai__pb2._PAI
_DOQIANGTINGPAIRESPONSE.fields_by_name['lastPai'].message_type = pai__pb2._PAI
_DOQIANGTINGPAIRESPONSE.fields_by_name['pai'].message_type = pai__pb2._PAI
_DOQIANGTINGPAIRESPONSE.fields_by_name['chipai'].message_type = pai__pb2._CHIPAI
_DOQIANGTINGPAIRESPONSE.fields_by_name['pengpai'].message_type = pai__pb2._PAI
_DOQIANGTINGPAINOTIFY.fields_by_name['pai'].message_type = pai__pb2._PAI
_DOQIANGTINGPAINOTIFY.fields_by_name['chipai'].message_type = pai__pb2._CHIPAI
_DOQIANGTINGPAINOTIFY.fields_by_name['pengpai'].message_type = pai__pb2._PAI
_DOQIANGTINGPAINOTIFY.fields_by_name['lastPai'].message_type = pai__pb2._PAI
DESCRIPTOR.message_types_by_name['DoQiangTingPaiRequest'] = _DOQIANGTINGPAIREQUEST
DESCRIPTOR.message_types_by_name['DoQiangTingPaiResponse'] = _DOQIANGTINGPAIRESPONSE
DESCRIPTOR.message_types_by_name['DoQiangTingPaiNotify'] = _DOQIANGTINGPAINOTIFY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DoQiangTingPaiRequest = _reflection.GeneratedProtocolMessageType('DoQiangTingPaiRequest', (_message.Message,), dict(
  DESCRIPTOR = _DOQIANGTINGPAIREQUEST,
  __module__ = 'do_qiang_ting_pai_pb2'
  # @@protoc_insertion_point(class_scope:DoQiangTingPaiRequest)
  ))
_sym_db.RegisterMessage(DoQiangTingPaiRequest)

DoQiangTingPaiResponse = _reflection.GeneratedProtocolMessageType('DoQiangTingPaiResponse', (_message.Message,), dict(
  DESCRIPTOR = _DOQIANGTINGPAIRESPONSE,
  __module__ = 'do_qiang_ting_pai_pb2'
  # @@protoc_insertion_point(class_scope:DoQiangTingPaiResponse)
  ))
_sym_db.RegisterMessage(DoQiangTingPaiResponse)

DoQiangTingPaiNotify = _reflection.GeneratedProtocolMessageType('DoQiangTingPaiNotify', (_message.Message,), dict(
  DESCRIPTOR = _DOQIANGTINGPAINOTIFY,
  __module__ = 'do_qiang_ting_pai_pb2'
  # @@protoc_insertion_point(class_scope:DoQiangTingPaiNotify)
  ))
_sym_db.RegisterMessage(DoQiangTingPaiNotify)


# @@protoc_insertion_point(module_scope)
