# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: do_ting_pai.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pai_pb2 as pai__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='do_ting_pai.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x11\x64o_ting_pai.proto\x1a\tpai.proto\"G\n\x10\x44oTingPaiRequest\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x0f\n\x07sRoomID\x18\x02 \x02(\t\x12\x11\n\x03pai\x18\x03 \x01(\x0b\x32\x04.Pai\"\'\n\x11\x44oTingPaiResponse\x12\x12\n\nnErrorCode\x18\x01 \x02(\x05\"F\n\x0f\x44oTingPaiNotify\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x0f\n\x07sRoomID\x18\x02 \x02(\t\x12\x11\n\x03pai\x18\x03 \x01(\x0b\x32\x04.Pai')
  ,
  dependencies=[pai__pb2.DESCRIPTOR,])




_DOTINGPAIREQUEST = _descriptor.Descriptor(
  name='DoTingPaiRequest',
  full_name='DoTingPaiRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='DoTingPaiRequest.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='DoTingPaiRequest.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pai', full_name='DoTingPaiRequest.pai', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=103,
)


_DOTINGPAIRESPONSE = _descriptor.Descriptor(
  name='DoTingPaiResponse',
  full_name='DoTingPaiResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nErrorCode', full_name='DoTingPaiResponse.nErrorCode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=144,
)


_DOTINGPAINOTIFY = _descriptor.Descriptor(
  name='DoTingPaiNotify',
  full_name='DoTingPaiNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='DoTingPaiNotify.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='DoTingPaiNotify.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pai', full_name='DoTingPaiNotify.pai', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=216,
)

_DOTINGPAIREQUEST.fields_by_name['pai'].message_type = pai__pb2._PAI
_DOTINGPAINOTIFY.fields_by_name['pai'].message_type = pai__pb2._PAI
DESCRIPTOR.message_types_by_name['DoTingPaiRequest'] = _DOTINGPAIREQUEST
DESCRIPTOR.message_types_by_name['DoTingPaiResponse'] = _DOTINGPAIRESPONSE
DESCRIPTOR.message_types_by_name['DoTingPaiNotify'] = _DOTINGPAINOTIFY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DoTingPaiRequest = _reflection.GeneratedProtocolMessageType('DoTingPaiRequest', (_message.Message,), dict(
  DESCRIPTOR = _DOTINGPAIREQUEST,
  __module__ = 'do_ting_pai_pb2'
  # @@protoc_insertion_point(class_scope:DoTingPaiRequest)
  ))
_sym_db.RegisterMessage(DoTingPaiRequest)

DoTingPaiResponse = _reflection.GeneratedProtocolMessageType('DoTingPaiResponse', (_message.Message,), dict(
  DESCRIPTOR = _DOTINGPAIRESPONSE,
  __module__ = 'do_ting_pai_pb2'
  # @@protoc_insertion_point(class_scope:DoTingPaiResponse)
  ))
_sym_db.RegisterMessage(DoTingPaiResponse)

DoTingPaiNotify = _reflection.GeneratedProtocolMessageType('DoTingPaiNotify', (_message.Message,), dict(
  DESCRIPTOR = _DOTINGPAINOTIFY,
  __module__ = 'do_ting_pai_pb2'
  # @@protoc_insertion_point(class_scope:DoTingPaiNotify)
  ))
_sym_db.RegisterMessage(DoTingPaiNotify)


# @@protoc_insertion_point(module_scope)
