# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gameplay.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gameplay.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0egameplay.proto\",\n\x08GamePlay\x12\r\n\x05nType\x18\x01 \x02(\x05\x12\x11\n\toptionals\x18\x02 \x03(\x05')
)




_GAMEPLAY = _descriptor.Descriptor(
  name='GamePlay',
  full_name='GamePlay',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nType', full_name='GamePlay.nType', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='optionals', full_name='GamePlay.optionals', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=62,
)

DESCRIPTOR.message_types_by_name['GamePlay'] = _GAMEPLAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GamePlay = _reflection.GeneratedProtocolMessageType('GamePlay', (_message.Message,), dict(
  DESCRIPTOR = _GAMEPLAY,
  __module__ = 'gameplay_pb2'
  # @@protoc_insertion_point(class_scope:GamePlay)
  ))
_sym_db.RegisterMessage(GamePlay)


# @@protoc_insertion_point(module_scope)
