# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pai_pb2 as pai__pb2
import login_pb2 as login__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gamer.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0bgamer.proto\x1a\tpai.proto\x1a\x0blogin.proto\"\xc2\x02\n\x05Gamer\x12\x0f\n\x07sRoomID\x18\x01 \x02(\t\x12\x0c\n\x04nGID\x18\x02 \x02(\x05\x12\x0c\n\x04nPos\x18\x03 \x02(\x05\x12\r\n\x05\x62\x42oss\x18\x04 \x02(\x08\x12\r\n\x05state\x18\x05 \x02(\x05\x12\x0e\n\x06\x62Owner\x18\x06 \x02(\x08\x12\r\n\x05sName\x18\x07 \x02(\t\x12\x12\n\nsHeadImage\x18\x08 \x02(\t\x12\x1e\n\x07paipool\x18\t \x01(\x0b\x32\r.GamerPaiPool\x12\x0f\n\x07\x62Online\x18\n \x01(\x08\x12\x12\n\ntotalScore\x18\x0b \x01(\x05\x12\x11\n\tgameState\x18\x0c \x01(\x05\x12\x0b\n\x03\x62\x41I\x18\r \x01(\x08\x12\x0f\n\x07nGender\x18\x0e \x01(\x05\x12\x13\n\x0bnAIRandInfo\x18\x0f \x01(\x05\x12\x13\n\x0bnAIRandHead\x18\x10 \x01(\x05\x12\x1b\n\x08location\x18\x11 \x01(\x0b\x32\t.Location')
  ,
  dependencies=[pai__pb2.DESCRIPTOR,login__pb2.DESCRIPTOR,])




_GAMER = _descriptor.Descriptor(
  name='Gamer',
  full_name='Gamer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='Gamer.sRoomID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nGID', full_name='Gamer.nGID', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nPos', full_name='Gamer.nPos', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bBoss', full_name='Gamer.bBoss', index=3,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='Gamer.state', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bOwner', full_name='Gamer.bOwner', index=5,
      number=6, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sName', full_name='Gamer.sName', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sHeadImage', full_name='Gamer.sHeadImage', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='paipool', full_name='Gamer.paipool', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bOnline', full_name='Gamer.bOnline', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='totalScore', full_name='Gamer.totalScore', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gameState', full_name='Gamer.gameState', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bAI', full_name='Gamer.bAI', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nGender', full_name='Gamer.nGender', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nAIRandInfo', full_name='Gamer.nAIRandInfo', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nAIRandHead', full_name='Gamer.nAIRandHead', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location', full_name='Gamer.location', index=16,
      number=17, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=362,
)

_GAMER.fields_by_name['paipool'].message_type = pai__pb2._GAMERPAIPOOL
_GAMER.fields_by_name['location'].message_type = login__pb2._LOCATION
DESCRIPTOR.message_types_by_name['Gamer'] = _GAMER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Gamer = _reflection.GeneratedProtocolMessageType('Gamer', (_message.Message,), dict(
  DESCRIPTOR = _GAMER,
  __module__ = 'gamer_pb2'
  # @@protoc_insertion_point(class_scope:Gamer)
  ))
_sym_db.RegisterMessage(Gamer)


# @@protoc_insertion_point(module_scope)
