# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_pai.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pai_pb2 as pai__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='get_pai.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\rget_pai.proto\x1a\tpai.proto\"D\n\x0cGetPaiNotify\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x14\n\x06getPai\x18\x02 \x02(\x0b\x32\x04.Pai\x12\r\n\x05nLeft\x18\x03 \x02(\x05')
  ,
  dependencies=[pai__pb2.DESCRIPTOR,])




_GETPAINOTIFY = _descriptor.Descriptor(
  name='GetPaiNotify',
  full_name='GetPaiNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='GetPaiNotify.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='getPai', full_name='GetPaiNotify.getPai', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nLeft', full_name='GetPaiNotify.nLeft', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=96,
)

_GETPAINOTIFY.fields_by_name['getPai'].message_type = pai__pb2._PAI
DESCRIPTOR.message_types_by_name['GetPaiNotify'] = _GETPAINOTIFY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetPaiNotify = _reflection.GeneratedProtocolMessageType('GetPaiNotify', (_message.Message,), dict(
  DESCRIPTOR = _GETPAINOTIFY,
  __module__ = 'get_pai_pb2'
  # @@protoc_insertion_point(class_scope:GetPaiNotify)
  ))
_sym_db.RegisterMessage(GetPaiNotify)


# @@protoc_insertion_point(module_scope)
