# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: join_room.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gamer_pb2 as gamer__pb2
import gameplay_pb2 as gameplay__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='join_room.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0fjoin_room.proto\x1a\x0bgamer.proto\x1a\x0egameplay.proto\"\xa3\x01\n\x04Room\x12\x0b\n\x03sID\x18\x01 \x02(\t\x12\x1b\n\x08gamePlay\x18\x02 \x02(\x0b\x32\t.GamePlay\x12\x16\n\x06Gamers\x18\x03 \x03(\x0b\x32\x06.Gamer\x12\x0e\n\x06nState\x18\x04 \x01(\x05\x12\x12\n\nnCardCount\x18\x05 \x01(\x05\x12\x10\n\x08nPlayers\x18\x06 \x01(\x05\x12\x11\n\tsCardType\x18\x07 \x01(\t\x12\x10\n\x08nOwnerID\x18\x08 \x01(\x05\"3\n\x0fJoinRoomRequest\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x0f\n\x07sRoomID\x18\x02 \x02(\t\"?\n\x10JoinRoomResponse\x12\x12\n\nnErrorCode\x18\x01 \x02(\x05\x12\x17\n\x08joinRoom\x18\x02 \x01(\x0b\x32\x05.Room\"+\n\x0eJoinRoomNotify\x12\x19\n\tjoinGamer\x18\x01 \x02(\x0b\x32\x06.Gamer')
  ,
  dependencies=[gamer__pb2.DESCRIPTOR,gameplay__pb2.DESCRIPTOR,])




_ROOM = _descriptor.Descriptor(
  name='Room',
  full_name='Room',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sID', full_name='Room.sID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gamePlay', full_name='Room.gamePlay', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Gamers', full_name='Room.Gamers', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nState', full_name='Room.nState', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nCardCount', full_name='Room.nCardCount', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nPlayers', full_name='Room.nPlayers', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sCardType', full_name='Room.sCardType', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nOwnerID', full_name='Room.nOwnerID', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=212,
)


_JOINROOMREQUEST = _descriptor.Descriptor(
  name='JoinRoomRequest',
  full_name='JoinRoomRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='JoinRoomRequest.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='JoinRoomRequest.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=265,
)


_JOINROOMRESPONSE = _descriptor.Descriptor(
  name='JoinRoomResponse',
  full_name='JoinRoomResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nErrorCode', full_name='JoinRoomResponse.nErrorCode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='joinRoom', full_name='JoinRoomResponse.joinRoom', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=330,
)


_JOINROOMNOTIFY = _descriptor.Descriptor(
  name='JoinRoomNotify',
  full_name='JoinRoomNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='joinGamer', full_name='JoinRoomNotify.joinGamer', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=332,
  serialized_end=375,
)

_ROOM.fields_by_name['gamePlay'].message_type = gameplay__pb2._GAMEPLAY
_ROOM.fields_by_name['Gamers'].message_type = gamer__pb2._GAMER
_JOINROOMRESPONSE.fields_by_name['joinRoom'].message_type = _ROOM
_JOINROOMNOTIFY.fields_by_name['joinGamer'].message_type = gamer__pb2._GAMER
DESCRIPTOR.message_types_by_name['Room'] = _ROOM
DESCRIPTOR.message_types_by_name['JoinRoomRequest'] = _JOINROOMREQUEST
DESCRIPTOR.message_types_by_name['JoinRoomResponse'] = _JOINROOMRESPONSE
DESCRIPTOR.message_types_by_name['JoinRoomNotify'] = _JOINROOMNOTIFY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Room = _reflection.GeneratedProtocolMessageType('Room', (_message.Message,), dict(
  DESCRIPTOR = _ROOM,
  __module__ = 'join_room_pb2'
  # @@protoc_insertion_point(class_scope:Room)
  ))
_sym_db.RegisterMessage(Room)

JoinRoomRequest = _reflection.GeneratedProtocolMessageType('JoinRoomRequest', (_message.Message,), dict(
  DESCRIPTOR = _JOINROOMREQUEST,
  __module__ = 'join_room_pb2'
  # @@protoc_insertion_point(class_scope:JoinRoomRequest)
  ))
_sym_db.RegisterMessage(JoinRoomRequest)

JoinRoomResponse = _reflection.GeneratedProtocolMessageType('JoinRoomResponse', (_message.Message,), dict(
  DESCRIPTOR = _JOINROOMRESPONSE,
  __module__ = 'join_room_pb2'
  # @@protoc_insertion_point(class_scope:JoinRoomResponse)
  ))
_sym_db.RegisterMessage(JoinRoomResponse)

JoinRoomNotify = _reflection.GeneratedProtocolMessageType('JoinRoomNotify', (_message.Message,), dict(
  DESCRIPTOR = _JOINROOMNOTIFY,
  __module__ = 'join_room_pb2'
  # @@protoc_insertion_point(class_scope:JoinRoomNotify)
  ))
_sym_db.RegisterMessage(JoinRoomNotify)


# @@protoc_insertion_point(module_scope)
