# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: leave_room.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='leave_room.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x10leave_room.proto\"4\n\x10LeaveRoomRequest\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x0f\n\x07sRoomID\x18\x02 \x02(\t\"6\n\x11LeaveRoomResponse\x12\x12\n\nnErrorCode\x18\x01 \x02(\x05\x12\r\n\x05\x62Kick\x18\x02 \x01(\x08\"B\n\x0fLeaveRoomNotify\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x0f\n\x07sRoomID\x18\x02 \x02(\t\x12\r\n\x05\x62Kick\x18\x03 \x01(\x08')
)




_LEAVEROOMREQUEST = _descriptor.Descriptor(
  name='LeaveRoomRequest',
  full_name='LeaveRoomRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='LeaveRoomRequest.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='LeaveRoomRequest.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=72,
)


_LEAVEROOMRESPONSE = _descriptor.Descriptor(
  name='LeaveRoomResponse',
  full_name='LeaveRoomResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nErrorCode', full_name='LeaveRoomResponse.nErrorCode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bKick', full_name='LeaveRoomResponse.bKick', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=128,
)


_LEAVEROOMNOTIFY = _descriptor.Descriptor(
  name='LeaveRoomNotify',
  full_name='LeaveRoomNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='LeaveRoomNotify.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='LeaveRoomNotify.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bKick', full_name='LeaveRoomNotify.bKick', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=196,
)

DESCRIPTOR.message_types_by_name['LeaveRoomRequest'] = _LEAVEROOMREQUEST
DESCRIPTOR.message_types_by_name['LeaveRoomResponse'] = _LEAVEROOMRESPONSE
DESCRIPTOR.message_types_by_name['LeaveRoomNotify'] = _LEAVEROOMNOTIFY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LeaveRoomRequest = _reflection.GeneratedProtocolMessageType('LeaveRoomRequest', (_message.Message,), dict(
  DESCRIPTOR = _LEAVEROOMREQUEST,
  __module__ = 'leave_room_pb2'
  # @@protoc_insertion_point(class_scope:LeaveRoomRequest)
  ))
_sym_db.RegisterMessage(LeaveRoomRequest)

LeaveRoomResponse = _reflection.GeneratedProtocolMessageType('LeaveRoomResponse', (_message.Message,), dict(
  DESCRIPTOR = _LEAVEROOMRESPONSE,
  __module__ = 'leave_room_pb2'
  # @@protoc_insertion_point(class_scope:LeaveRoomResponse)
  ))
_sym_db.RegisterMessage(LeaveRoomResponse)

LeaveRoomNotify = _reflection.GeneratedProtocolMessageType('LeaveRoomNotify', (_message.Message,), dict(
  DESCRIPTOR = _LEAVEROOMNOTIFY,
  __module__ = 'leave_room_pb2'
  # @@protoc_insertion_point(class_scope:LeaveRoomNotify)
  ))
_sym_db.RegisterMessage(LeaveRoomNotify)


# @@protoc_insertion_point(module_scope)
