# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='log.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\tlog.proto\"5\n\x10\x43lientLogRequest\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x10\n\x08sContent\x18\x02 \x02(\t')
)




_CLIENTLOGREQUEST = _descriptor.Descriptor(
  name='ClientLogRequest',
  full_name='ClientLogRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='ClientLogRequest.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sContent', full_name='ClientLogRequest.sContent', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=66,
)

DESCRIPTOR.message_types_by_name['ClientLogRequest'] = _CLIENTLOGREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientLogRequest = _reflection.GeneratedProtocolMessageType('ClientLogRequest', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTLOGREQUEST,
  __module__ = 'log_pb2'
  # @@protoc_insertion_point(class_scope:ClientLogRequest)
  ))
_sym_db.RegisterMessage(ClientLogRequest)


# @@protoc_insertion_point(module_scope)
