# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login_heart.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='login_heart.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x11login_heart.proto\"4\n\x11LoginHeartRequest\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x0e\n\x06sToken\x18\x02 \x02(\t\";\n\x12LoginHeartResponse\x12\x12\n\nnErrorCode\x18\x01 \x02(\x05\x12\x11\n\tnHappyNum\x18\x02 \x01(\x05')
)




_LOGINHEARTREQUEST = _descriptor.Descriptor(
  name='LoginHeartRequest',
  full_name='LoginHeartRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='LoginHeartRequest.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sToken', full_name='LoginHeartRequest.sToken', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=73,
)


_LOGINHEARTRESPONSE = _descriptor.Descriptor(
  name='LoginHeartResponse',
  full_name='LoginHeartResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nErrorCode', full_name='LoginHeartResponse.nErrorCode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nHappyNum', full_name='LoginHeartResponse.nHappyNum', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=134,
)

DESCRIPTOR.message_types_by_name['LoginHeartRequest'] = _LOGINHEARTREQUEST
DESCRIPTOR.message_types_by_name['LoginHeartResponse'] = _LOGINHEARTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoginHeartRequest = _reflection.GeneratedProtocolMessageType('LoginHeartRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOGINHEARTREQUEST,
  __module__ = 'login_heart_pb2'
  # @@protoc_insertion_point(class_scope:LoginHeartRequest)
  ))
_sym_db.RegisterMessage(LoginHeartRequest)

LoginHeartResponse = _reflection.GeneratedProtocolMessageType('LoginHeartResponse', (_message.Message,), dict(
  DESCRIPTOR = _LOGINHEARTRESPONSE,
  __module__ = 'login_heart_pb2'
  # @@protoc_insertion_point(class_scope:LoginHeartResponse)
  ))
_sym_db.RegisterMessage(LoginHeartResponse)


# @@protoc_insertion_point(module_scope)
