# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lucky.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import assets_pb2 as assets__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lucky.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0blucky.proto\x1a\x0c\x61ssets.proto\"\x1f\n\x0cLuckyRequest\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\"T\n\rLuckyResponse\x12\x12\n\nnErrorCode\x18\x01 \x02(\x05\x12\x1f\n\tnewAssets\x18\x02 \x01(\x0b\x32\x0c.AssetUpdate\x12\x0e\n\x06nLucky\x18\x03 \x01(\x05')
  ,
  dependencies=[assets__pb2.DESCRIPTOR,])




_LUCKYREQUEST = _descriptor.Descriptor(
  name='LuckyRequest',
  full_name='LuckyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='LuckyRequest.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=60,
)


_LUCKYRESPONSE = _descriptor.Descriptor(
  name='LuckyResponse',
  full_name='LuckyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nErrorCode', full_name='LuckyResponse.nErrorCode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='newAssets', full_name='LuckyResponse.newAssets', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nLucky', full_name='LuckyResponse.nLucky', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=146,
)

_LUCKYRESPONSE.fields_by_name['newAssets'].message_type = assets__pb2._ASSETUPDATE
DESCRIPTOR.message_types_by_name['LuckyRequest'] = _LUCKYREQUEST
DESCRIPTOR.message_types_by_name['LuckyResponse'] = _LUCKYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LuckyRequest = _reflection.GeneratedProtocolMessageType('LuckyRequest', (_message.Message,), dict(
  DESCRIPTOR = _LUCKYREQUEST,
  __module__ = 'lucky_pb2'
  # @@protoc_insertion_point(class_scope:LuckyRequest)
  ))
_sym_db.RegisterMessage(LuckyRequest)

LuckyResponse = _reflection.GeneratedProtocolMessageType('LuckyResponse', (_message.Message,), dict(
  DESCRIPTOR = _LUCKYRESPONSE,
  __module__ = 'lucky_pb2'
  # @@protoc_insertion_point(class_scope:LuckyResponse)
  ))
_sym_db.RegisterMessage(LuckyResponse)


# @@protoc_insertion_point(module_scope)
