# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mail.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mail.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\nmail.proto\"Q\n\x04Mail\x12\x0b\n\x03nID\x18\x01 \x02(\x05\x12\x0c\n\x04nUID\x18\x02 \x01(\x05\x12\r\n\x05nType\x18\x03 \x01(\x05\x12\x10\n\x08sContent\x18\x04 \x01(\t\x12\r\n\x05sTime\x18\x05 \x01(\t\"\x1e\n\x0bMailRequest\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\"8\n\x0cMailResponse\x12\x12\n\nnErrorCode\x18\x01 \x02(\x05\x12\x14\n\x05mails\x18\x02 \x03(\x0b\x32\x05.Mail')
)




_MAIL = _descriptor.Descriptor(
  name='Mail',
  full_name='Mail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nID', full_name='Mail.nID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nUID', full_name='Mail.nUID', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nType', full_name='Mail.nType', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sContent', full_name='Mail.sContent', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sTime', full_name='Mail.sTime', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=95,
)


_MAILREQUEST = _descriptor.Descriptor(
  name='MailRequest',
  full_name='MailRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='MailRequest.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=127,
)


_MAILRESPONSE = _descriptor.Descriptor(
  name='MailResponse',
  full_name='MailResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nErrorCode', full_name='MailResponse.nErrorCode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mails', full_name='MailResponse.mails', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=185,
)

_MAILRESPONSE.fields_by_name['mails'].message_type = _MAIL
DESCRIPTOR.message_types_by_name['Mail'] = _MAIL
DESCRIPTOR.message_types_by_name['MailRequest'] = _MAILREQUEST
DESCRIPTOR.message_types_by_name['MailResponse'] = _MAILRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Mail = _reflection.GeneratedProtocolMessageType('Mail', (_message.Message,), dict(
  DESCRIPTOR = _MAIL,
  __module__ = 'mail_pb2'
  # @@protoc_insertion_point(class_scope:Mail)
  ))
_sym_db.RegisterMessage(Mail)

MailRequest = _reflection.GeneratedProtocolMessageType('MailRequest', (_message.Message,), dict(
  DESCRIPTOR = _MAILREQUEST,
  __module__ = 'mail_pb2'
  # @@protoc_insertion_point(class_scope:MailRequest)
  ))
_sym_db.RegisterMessage(MailRequest)

MailResponse = _reflection.GeneratedProtocolMessageType('MailResponse', (_message.Message,), dict(
  DESCRIPTOR = _MAILRESPONSE,
  __module__ = 'mail_pb2'
  # @@protoc_insertion_point(class_scope:MailResponse)
  ))
_sym_db.RegisterMessage(MailResponse)


# @@protoc_insertion_point(module_scope)
