# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: netconnect.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='netconnect.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x10netconnect.proto\"1\n\rConnectNotify\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x0f\n\x07sRoomID\x18\x02 \x02(\t\"4\n\x10\x44isConnectNotify\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x0f\n\x07sRoomID\x18\x02 \x02(\t')
)




_CONNECTNOTIFY = _descriptor.Descriptor(
  name='ConnectNotify',
  full_name='ConnectNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='ConnectNotify.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='ConnectNotify.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=69,
)


_DISCONNECTNOTIFY = _descriptor.Descriptor(
  name='DisConnectNotify',
  full_name='DisConnectNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='DisConnectNotify.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='DisConnectNotify.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=123,
)

DESCRIPTOR.message_types_by_name['ConnectNotify'] = _CONNECTNOTIFY
DESCRIPTOR.message_types_by_name['DisConnectNotify'] = _DISCONNECTNOTIFY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConnectNotify = _reflection.GeneratedProtocolMessageType('ConnectNotify', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTNOTIFY,
  __module__ = 'netconnect_pb2'
  # @@protoc_insertion_point(class_scope:ConnectNotify)
  ))
_sym_db.RegisterMessage(ConnectNotify)

DisConnectNotify = _reflection.GeneratedProtocolMessageType('DisConnectNotify', (_message.Message,), dict(
  DESCRIPTOR = _DISCONNECTNOTIFY,
  __module__ = 'netconnect_pb2'
  # @@protoc_insertion_point(class_scope:DisConnectNotify)
  ))
_sym_db.RegisterMessage(DisConnectNotify)


# @@protoc_insertion_point(module_scope)
