# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: owner_change.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='owner_change.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x12owner_change.proto\"%\n\x11OwnerChangeNotify\x12\x10\n\x08nOwnerID\x18\x01 \x02(\x05')
)




_OWNERCHANGENOTIFY = _descriptor.Descriptor(
  name='OwnerChangeNotify',
  full_name='OwnerChangeNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nOwnerID', full_name='OwnerChangeNotify.nOwnerID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=59,
)

DESCRIPTOR.message_types_by_name['OwnerChangeNotify'] = _OWNERCHANGENOTIFY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OwnerChangeNotify = _reflection.GeneratedProtocolMessageType('OwnerChangeNotify', (_message.Message,), dict(
  DESCRIPTOR = _OWNERCHANGENOTIFY,
  __module__ = 'owner_change_pb2'
  # @@protoc_insertion_point(class_scope:OwnerChangeNotify)
  ))
_sym_db.RegisterMessage(OwnerChangeNotify)


# @@protoc_insertion_point(module_scope)
