# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: put_pai.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pai_pb2 as pai__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='put_pai.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\rput_pai.proto\x1a\tpai.proto\"G\n\rPutPaiRequest\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x0f\n\x07sRoomID\x18\x02 \x02(\t\x12\x14\n\x06putPai\x18\x03 \x02(\x0b\x32\x04.Pai\":\n\x0ePutPaiResponse\x12\x12\n\nnErrorCode\x18\x01 \x02(\x05\x12\x14\n\x06putPai\x18\x02 \x01(\x0b\x32\x04.Pai\"5\n\x0cPutPaiNotify\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x14\n\x06putPai\x18\x02 \x02(\x0b\x32\x04.Pai\"S\n\x0e\x44oPutPaiNotify\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x11\n\tnPutState\x18\x02 \x02(\x05\x12\x1d\n\x06huPais\x18\x03 \x03(\x0b\x32\r.CanHuPaiPool')
  ,
  dependencies=[pai__pb2.DESCRIPTOR,])




_PUTPAIREQUEST = _descriptor.Descriptor(
  name='PutPaiRequest',
  full_name='PutPaiRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='PutPaiRequest.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='PutPaiRequest.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='putPai', full_name='PutPaiRequest.putPai', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=99,
)


_PUTPAIRESPONSE = _descriptor.Descriptor(
  name='PutPaiResponse',
  full_name='PutPaiResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nErrorCode', full_name='PutPaiResponse.nErrorCode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='putPai', full_name='PutPaiResponse.putPai', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=159,
)


_PUTPAINOTIFY = _descriptor.Descriptor(
  name='PutPaiNotify',
  full_name='PutPaiNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='PutPaiNotify.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='putPai', full_name='PutPaiNotify.putPai', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=214,
)


_DOPUTPAINOTIFY = _descriptor.Descriptor(
  name='DoPutPaiNotify',
  full_name='DoPutPaiNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='DoPutPaiNotify.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nPutState', full_name='DoPutPaiNotify.nPutState', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='huPais', full_name='DoPutPaiNotify.huPais', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=299,
)

_PUTPAIREQUEST.fields_by_name['putPai'].message_type = pai__pb2._PAI
_PUTPAIRESPONSE.fields_by_name['putPai'].message_type = pai__pb2._PAI
_PUTPAINOTIFY.fields_by_name['putPai'].message_type = pai__pb2._PAI
_DOPUTPAINOTIFY.fields_by_name['huPais'].message_type = pai__pb2._CANHUPAIPOOL
DESCRIPTOR.message_types_by_name['PutPaiRequest'] = _PUTPAIREQUEST
DESCRIPTOR.message_types_by_name['PutPaiResponse'] = _PUTPAIRESPONSE
DESCRIPTOR.message_types_by_name['PutPaiNotify'] = _PUTPAINOTIFY
DESCRIPTOR.message_types_by_name['DoPutPaiNotify'] = _DOPUTPAINOTIFY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PutPaiRequest = _reflection.GeneratedProtocolMessageType('PutPaiRequest', (_message.Message,), dict(
  DESCRIPTOR = _PUTPAIREQUEST,
  __module__ = 'put_pai_pb2'
  # @@protoc_insertion_point(class_scope:PutPaiRequest)
  ))
_sym_db.RegisterMessage(PutPaiRequest)

PutPaiResponse = _reflection.GeneratedProtocolMessageType('PutPaiResponse', (_message.Message,), dict(
  DESCRIPTOR = _PUTPAIRESPONSE,
  __module__ = 'put_pai_pb2'
  # @@protoc_insertion_point(class_scope:PutPaiResponse)
  ))
_sym_db.RegisterMessage(PutPaiResponse)

PutPaiNotify = _reflection.GeneratedProtocolMessageType('PutPaiNotify', (_message.Message,), dict(
  DESCRIPTOR = _PUTPAINOTIFY,
  __module__ = 'put_pai_pb2'
  # @@protoc_insertion_point(class_scope:PutPaiNotify)
  ))
_sym_db.RegisterMessage(PutPaiNotify)

DoPutPaiNotify = _reflection.GeneratedProtocolMessageType('DoPutPaiNotify', (_message.Message,), dict(
  DESCRIPTOR = _DOPUTPAINOTIFY,
  __module__ = 'put_pai_pb2'
  # @@protoc_insertion_point(class_scope:DoPutPaiNotify)
  ))
_sym_db.RegisterMessage(DoPutPaiNotify)


# @@protoc_insertion_point(module_scope)
