# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rank.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import assets_pb2 as assets__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rank.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\nrank.proto\x1a\x0c\x61ssets.proto\"\xaf\x01\n\nRankRecord\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x11\n\tnWinCount\x18\x02 \x02(\x05\x12\x0e\n\x06nScore\x18\x03 \x02(\x05\x12\r\n\x05sName\x18\x04 \x01(\t\x12\x10\n\x08sHeadimg\x18\x05 \x01(\t\x12\r\n\x05nRank\x18\x06 \x01(\x05\x12\x12\n\nnRankAward\x18\x07 \x01(\x05\x12\x16\n\x0enRankAwardType\x18\x08 \x01(\x05\x12\x11\n\tbCanAward\x18\t \x01(\x08\"T\n\rRankRecordAll\x12!\n\x0crankRequster\x18\x01 \x02(\x0b\x32\x0b.RankRecord\x12 \n\x0brankRecords\x18\x02 \x03(\x0b\x32\x0b.RankRecord\"\x1e\n\x0bRankRequest\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\"\xc6\x01\n\x0cRankResponse\x12\x12\n\nnErrorCode\x18\x01 \x02(\x05\x12&\n\x0erankDayRecords\x18\x02 \x02(\x0b\x32\x0e.RankRecordAll\x12\'\n\x0frankWeekRecords\x18\x03 \x02(\x0b\x32\x0e.RankRecordAll\x12(\n\x10rankMonthRecords\x18\x04 \x02(\x0b\x32\x0e.RankRecordAll\x12\'\n\x0frankYearRecords\x18\x05 \x02(\x0b\x32\x0e.RankRecordAll\"6\n\x10RankAwardRequest\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x11\n\tnRankType\x18\x02 \x02(\x05\"H\n\x11RankAwardResponse\x12\x12\n\nnErrorCode\x18\x01 \x02(\x05\x12\x1f\n\tnewAssets\x18\x02 \x01(\x0b\x32\x0c.AssetUpdate')
  ,
  dependencies=[assets__pb2.DESCRIPTOR,])




_RANKRECORD = _descriptor.Descriptor(
  name='RankRecord',
  full_name='RankRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='RankRecord.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nWinCount', full_name='RankRecord.nWinCount', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nScore', full_name='RankRecord.nScore', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sName', full_name='RankRecord.sName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sHeadimg', full_name='RankRecord.sHeadimg', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nRank', full_name='RankRecord.nRank', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nRankAward', full_name='RankRecord.nRankAward', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nRankAwardType', full_name='RankRecord.nRankAwardType', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bCanAward', full_name='RankRecord.bCanAward', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=204,
)


_RANKRECORDALL = _descriptor.Descriptor(
  name='RankRecordAll',
  full_name='RankRecordAll',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rankRequster', full_name='RankRecordAll.rankRequster', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rankRecords', full_name='RankRecordAll.rankRecords', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=290,
)


_RANKREQUEST = _descriptor.Descriptor(
  name='RankRequest',
  full_name='RankRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='RankRequest.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=292,
  serialized_end=322,
)


_RANKRESPONSE = _descriptor.Descriptor(
  name='RankResponse',
  full_name='RankResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nErrorCode', full_name='RankResponse.nErrorCode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rankDayRecords', full_name='RankResponse.rankDayRecords', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rankWeekRecords', full_name='RankResponse.rankWeekRecords', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rankMonthRecords', full_name='RankResponse.rankMonthRecords', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rankYearRecords', full_name='RankResponse.rankYearRecords', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=523,
)


_RANKAWARDREQUEST = _descriptor.Descriptor(
  name='RankAwardRequest',
  full_name='RankAwardRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='RankAwardRequest.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nRankType', full_name='RankAwardRequest.nRankType', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=525,
  serialized_end=579,
)


_RANKAWARDRESPONSE = _descriptor.Descriptor(
  name='RankAwardResponse',
  full_name='RankAwardResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nErrorCode', full_name='RankAwardResponse.nErrorCode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='newAssets', full_name='RankAwardResponse.newAssets', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=581,
  serialized_end=653,
)

_RANKRECORDALL.fields_by_name['rankRequster'].message_type = _RANKRECORD
_RANKRECORDALL.fields_by_name['rankRecords'].message_type = _RANKRECORD
_RANKRESPONSE.fields_by_name['rankDayRecords'].message_type = _RANKRECORDALL
_RANKRESPONSE.fields_by_name['rankWeekRecords'].message_type = _RANKRECORDALL
_RANKRESPONSE.fields_by_name['rankMonthRecords'].message_type = _RANKRECORDALL
_RANKRESPONSE.fields_by_name['rankYearRecords'].message_type = _RANKRECORDALL
_RANKAWARDRESPONSE.fields_by_name['newAssets'].message_type = assets__pb2._ASSETUPDATE
DESCRIPTOR.message_types_by_name['RankRecord'] = _RANKRECORD
DESCRIPTOR.message_types_by_name['RankRecordAll'] = _RANKRECORDALL
DESCRIPTOR.message_types_by_name['RankRequest'] = _RANKREQUEST
DESCRIPTOR.message_types_by_name['RankResponse'] = _RANKRESPONSE
DESCRIPTOR.message_types_by_name['RankAwardRequest'] = _RANKAWARDREQUEST
DESCRIPTOR.message_types_by_name['RankAwardResponse'] = _RANKAWARDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RankRecord = _reflection.GeneratedProtocolMessageType('RankRecord', (_message.Message,), dict(
  DESCRIPTOR = _RANKRECORD,
  __module__ = 'rank_pb2'
  # @@protoc_insertion_point(class_scope:RankRecord)
  ))
_sym_db.RegisterMessage(RankRecord)

RankRecordAll = _reflection.GeneratedProtocolMessageType('RankRecordAll', (_message.Message,), dict(
  DESCRIPTOR = _RANKRECORDALL,
  __module__ = 'rank_pb2'
  # @@protoc_insertion_point(class_scope:RankRecordAll)
  ))
_sym_db.RegisterMessage(RankRecordAll)

RankRequest = _reflection.GeneratedProtocolMessageType('RankRequest', (_message.Message,), dict(
  DESCRIPTOR = _RANKREQUEST,
  __module__ = 'rank_pb2'
  # @@protoc_insertion_point(class_scope:RankRequest)
  ))
_sym_db.RegisterMessage(RankRequest)

RankResponse = _reflection.GeneratedProtocolMessageType('RankResponse', (_message.Message,), dict(
  DESCRIPTOR = _RANKRESPONSE,
  __module__ = 'rank_pb2'
  # @@protoc_insertion_point(class_scope:RankResponse)
  ))
_sym_db.RegisterMessage(RankResponse)

RankAwardRequest = _reflection.GeneratedProtocolMessageType('RankAwardRequest', (_message.Message,), dict(
  DESCRIPTOR = _RANKAWARDREQUEST,
  __module__ = 'rank_pb2'
  # @@protoc_insertion_point(class_scope:RankAwardRequest)
  ))
_sym_db.RegisterMessage(RankAwardRequest)

RankAwardResponse = _reflection.GeneratedProtocolMessageType('RankAwardResponse', (_message.Message,), dict(
  DESCRIPTOR = _RANKAWARDRESPONSE,
  __module__ = 'rank_pb2'
  # @@protoc_insertion_point(class_scope:RankAwardResponse)
  ))
_sym_db.RegisterMessage(RankAwardResponse)


# @@protoc_insertion_point(module_scope)
