# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recharge.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='recharge.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0erecharge.proto\"0\n\x0fRechargeRequest\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x0c\n\x04nRMB\x18\x02 \x02(\x05\"8\n\x10RechargeResponse\x12\x12\n\nnErrorCode\x18\x01 \x02(\x05\x12\x10\n\x08nCrystal\x18\x02 \x01(\x05')
)




_RECHARGEREQUEST = _descriptor.Descriptor(
  name='RechargeRequest',
  full_name='RechargeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='RechargeRequest.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nRMB', full_name='RechargeRequest.nRMB', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=66,
)


_RECHARGERESPONSE = _descriptor.Descriptor(
  name='RechargeResponse',
  full_name='RechargeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nErrorCode', full_name='RechargeResponse.nErrorCode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nCrystal', full_name='RechargeResponse.nCrystal', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=124,
)

DESCRIPTOR.message_types_by_name['RechargeRequest'] = _RECHARGEREQUEST
DESCRIPTOR.message_types_by_name['RechargeResponse'] = _RECHARGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RechargeRequest = _reflection.GeneratedProtocolMessageType('RechargeRequest', (_message.Message,), dict(
  DESCRIPTOR = _RECHARGEREQUEST,
  __module__ = 'recharge_pb2'
  # @@protoc_insertion_point(class_scope:RechargeRequest)
  ))
_sym_db.RegisterMessage(RechargeRequest)

RechargeResponse = _reflection.GeneratedProtocolMessageType('RechargeResponse', (_message.Message,), dict(
  DESCRIPTOR = _RECHARGERESPONSE,
  __module__ = 'recharge_pb2'
  # @@protoc_insertion_point(class_scope:RechargeResponse)
  ))
_sym_db.RegisterMessage(RechargeResponse)


# @@protoc_insertion_point(module_scope)
