# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: start_game.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pai_pb2 as pai__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='start_game.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x10start_game.proto\x1a\tpai.proto\">\n\rInitPaiNotify\x12\x1e\n\x07paiPool\x18\x01 \x03(\x0b\x32\r.GamerPaiPool\x12\r\n\x05nLeft\x18\x03 \x02(\x05\"3\n\x0fStartGameNotify\x12\x0f\n\x07sRoomID\x18\x01 \x02(\t\x12\x0f\n\x07nBossID\x18\x02 \x02(\x05\"4\n\x10ReadyGameRequest\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x0f\n\x07sRoomID\x18\x02 \x02(\t\"\'\n\x11ReadyGameResponse\x12\x12\n\nnErrorCode\x18\x01 \x02(\x05\"3\n\x0fReadyGameNotify\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x0f\n\x07sRoomID\x18\x02 \x02(\t')
  ,
  dependencies=[pai__pb2.DESCRIPTOR,])




_INITPAINOTIFY = _descriptor.Descriptor(
  name='InitPaiNotify',
  full_name='InitPaiNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='paiPool', full_name='InitPaiNotify.paiPool', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nLeft', full_name='InitPaiNotify.nLeft', index=1,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=93,
)


_STARTGAMENOTIFY = _descriptor.Descriptor(
  name='StartGameNotify',
  full_name='StartGameNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='StartGameNotify.sRoomID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nBossID', full_name='StartGameNotify.nBossID', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=146,
)


_READYGAMEREQUEST = _descriptor.Descriptor(
  name='ReadyGameRequest',
  full_name='ReadyGameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='ReadyGameRequest.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='ReadyGameRequest.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=200,
)


_READYGAMERESPONSE = _descriptor.Descriptor(
  name='ReadyGameResponse',
  full_name='ReadyGameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nErrorCode', full_name='ReadyGameResponse.nErrorCode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=241,
)


_READYGAMENOTIFY = _descriptor.Descriptor(
  name='ReadyGameNotify',
  full_name='ReadyGameNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='ReadyGameNotify.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sRoomID', full_name='ReadyGameNotify.sRoomID', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=294,
)

_INITPAINOTIFY.fields_by_name['paiPool'].message_type = pai__pb2._GAMERPAIPOOL
DESCRIPTOR.message_types_by_name['InitPaiNotify'] = _INITPAINOTIFY
DESCRIPTOR.message_types_by_name['StartGameNotify'] = _STARTGAMENOTIFY
DESCRIPTOR.message_types_by_name['ReadyGameRequest'] = _READYGAMEREQUEST
DESCRIPTOR.message_types_by_name['ReadyGameResponse'] = _READYGAMERESPONSE
DESCRIPTOR.message_types_by_name['ReadyGameNotify'] = _READYGAMENOTIFY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InitPaiNotify = _reflection.GeneratedProtocolMessageType('InitPaiNotify', (_message.Message,), dict(
  DESCRIPTOR = _INITPAINOTIFY,
  __module__ = 'start_game_pb2'
  # @@protoc_insertion_point(class_scope:InitPaiNotify)
  ))
_sym_db.RegisterMessage(InitPaiNotify)

StartGameNotify = _reflection.GeneratedProtocolMessageType('StartGameNotify', (_message.Message,), dict(
  DESCRIPTOR = _STARTGAMENOTIFY,
  __module__ = 'start_game_pb2'
  # @@protoc_insertion_point(class_scope:StartGameNotify)
  ))
_sym_db.RegisterMessage(StartGameNotify)

ReadyGameRequest = _reflection.GeneratedProtocolMessageType('ReadyGameRequest', (_message.Message,), dict(
  DESCRIPTOR = _READYGAMEREQUEST,
  __module__ = 'start_game_pb2'
  # @@protoc_insertion_point(class_scope:ReadyGameRequest)
  ))
_sym_db.RegisterMessage(ReadyGameRequest)

ReadyGameResponse = _reflection.GeneratedProtocolMessageType('ReadyGameResponse', (_message.Message,), dict(
  DESCRIPTOR = _READYGAMERESPONSE,
  __module__ = 'start_game_pb2'
  # @@protoc_insertion_point(class_scope:ReadyGameResponse)
  ))
_sym_db.RegisterMessage(ReadyGameResponse)

ReadyGameNotify = _reflection.GeneratedProtocolMessageType('ReadyGameNotify', (_message.Message,), dict(
  DESCRIPTOR = _READYGAMENOTIFY,
  __module__ = 'start_game_pb2'
  # @@protoc_insertion_point(class_scope:ReadyGameNotify)
  ))
_sym_db.RegisterMessage(ReadyGameNotify)


# @@protoc_insertion_point(module_scope)
