# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: suggest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='suggest.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\rsuggest.proto\"C\n\x0eSuggestRequest\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\x12\x0e\n\x06sPhone\x18\x02 \x02(\t\x12\x10\n\x08sSuggest\x18\x03 \x02(\t\"%\n\x0fSuggestResponse\x12\x12\n\nnErrorCode\x18\x01 \x02(\x05')
)




_SUGGESTREQUEST = _descriptor.Descriptor(
  name='SuggestRequest',
  full_name='SuggestRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='SuggestRequest.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sPhone', full_name='SuggestRequest.sPhone', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sSuggest', full_name='SuggestRequest.sSuggest', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=84,
)


_SUGGESTRESPONSE = _descriptor.Descriptor(
  name='SuggestResponse',
  full_name='SuggestResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nErrorCode', full_name='SuggestResponse.nErrorCode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=123,
)

DESCRIPTOR.message_types_by_name['SuggestRequest'] = _SUGGESTREQUEST
DESCRIPTOR.message_types_by_name['SuggestResponse'] = _SUGGESTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SuggestRequest = _reflection.GeneratedProtocolMessageType('SuggestRequest', (_message.Message,), dict(
  DESCRIPTOR = _SUGGESTREQUEST,
  __module__ = 'suggest_pb2'
  # @@protoc_insertion_point(class_scope:SuggestRequest)
  ))
_sym_db.RegisterMessage(SuggestRequest)

SuggestResponse = _reflection.GeneratedProtocolMessageType('SuggestResponse', (_message.Message,), dict(
  DESCRIPTOR = _SUGGESTRESPONSE,
  __module__ = 'suggest_pb2'
  # @@protoc_insertion_point(class_scope:SuggestResponse)
  ))
_sym_db.RegisterMessage(SuggestResponse)


# @@protoc_insertion_point(module_scope)
