# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: welfare.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import assets_pb2 as assets__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='welfare.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\rwelfare.proto\x1a\x0c\x61ssets.proto\"!\n\x0eWelfareRequest\x12\x0f\n\x07nUserID\x18\x01 \x02(\x05\"F\n\x0fWelfareResponse\x12\x12\n\nnErrorCode\x18\x01 \x02(\x05\x12\x1f\n\tnewAssets\x18\x02 \x01(\x0b\x32\x0c.AssetUpdate')
  ,
  dependencies=[assets__pb2.DESCRIPTOR,])




_WELFAREREQUEST = _descriptor.Descriptor(
  name='WelfareRequest',
  full_name='WelfareRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nUserID', full_name='WelfareRequest.nUserID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=64,
)


_WELFARERESPONSE = _descriptor.Descriptor(
  name='WelfareResponse',
  full_name='WelfareResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nErrorCode', full_name='WelfareResponse.nErrorCode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='newAssets', full_name='WelfareResponse.newAssets', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=136,
)

_WELFARERESPONSE.fields_by_name['newAssets'].message_type = assets__pb2._ASSETUPDATE
DESCRIPTOR.message_types_by_name['WelfareRequest'] = _WELFAREREQUEST
DESCRIPTOR.message_types_by_name['WelfareResponse'] = _WELFARERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WelfareRequest = _reflection.GeneratedProtocolMessageType('WelfareRequest', (_message.Message,), dict(
  DESCRIPTOR = _WELFAREREQUEST,
  __module__ = 'welfare_pb2'
  # @@protoc_insertion_point(class_scope:WelfareRequest)
  ))
_sym_db.RegisterMessage(WelfareRequest)

WelfareResponse = _reflection.GeneratedProtocolMessageType('WelfareResponse', (_message.Message,), dict(
  DESCRIPTOR = _WELFARERESPONSE,
  __module__ = 'welfare_pb2'
  # @@protoc_insertion_point(class_scope:WelfareResponse)
  ))
_sym_db.RegisterMessage(WelfareResponse)


# @@protoc_insertion_point(module_scope)
